language: php
dist: xenial
os: linux

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

stages:
  - coding-standard
  - test

jobs:
  allow_failures:
    - php: nightly
  include:
    ## SNIFF STAGE ##
    - stage: coding-standard
      php: 7.4
      before_install:
      before_script:
      script: ./vendor/bin/phpcs -s
      after_script:

    ## TEST STAGE ##
    # Extra builds on top of those defined via the "php:" key.
    - stage: test
      php: 7.4
      env: CODE_COVERAGE=1

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix

install:
  - if [ "$CODE_COVERAGE" != 1 ]; then phpenv config-rm xdebug.ini || true; fi
  - composer install --no-interaction

before_script:
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
  - mkdir -p build/logs
  - cp test/testbootstrap-dist.php test/testbootstrap.php
  - chmod +x test/fakesendmail.sh
  - sudo mkdir -p /var/qmail/bin
  - sudo cp test/fakesendmail.sh /var/qmail/bin/sendmail
  - sudo cp test/fakesendmail.sh /usr/sbin/sendmail
  - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' > $(php --ini|grep -m 1 "ini files in:"|cut -d ":" -f 2)/sendmail.ini

script:
  - ./vendor/bin/phpunit --configuration ./travis.phpunit.xml.dist

after_script:
  - if [ "$CODE_COVERAGE" = 1 ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$CODE_COVERAGE" = 1 ]; then php ocular.phar code-coverage:upload --format=php-clover ../build/logs/clover.xml; fi
