name: Create Archive and Scan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'veracode.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
        
    - name: Veracode Upload And Scan
      # You may pin to the exact commit or the version.
      # uses: veracode/veracode-uploadandscan-action@c3c0b78bddb42d5f6b10d70562f692215a410d7b
      uses: veracode/veracode-uploadandscan-action@v1.0
      with:
      # appname
      appname: PHPMailer
      # createprofile
      createprofile: true
      # filepath
      filepath: 
      # version
      version: ${{ github.run_id }}
      # vid
      vid: ${{ secrets.VERACODE_API_ID }}
      # vkey
      vkey: ${{ secrets.VERACODE_API_KEY }} 
