name: Create Archive and Scan
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'veracode.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
        
    - name: Veracode Scan
      run:  .scripts/VeracodeScan.sh $VERACODE_API_ID $VERACODE_API_KEY "PHPMailer" "veracode.zip" "Test scan"          
